
/**
* Resources
* ---------
* This file is auto-generated by a tool
**/
angular.module('ngLiteral', [])
.factory('ngLiteral', [function (ServicesController) {

return { 
'es-ES': {   
	ToastPeticionRealizadaCorrectamente : 'Peticion realizada correctamente',		
}
};
    
}]);

